name: Build and publish to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo # (callout-1)
        uses: actions/checkout@v2
      - name: Build image api # (callout-2)
        run: |
          chmod +x ./docker/build_web_prod.sh
          ./docker/build_web_prod.sh
        shell: bash
      - name: Build image web
        run: |
          chmod +x ../../docker/build_api_prod.sh
          ../../docker/build_api_prod.sh
        shell: bash
      - name: Install doctl # (callout-3)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry # (callout-4)
        run: doctl registry login --expiry-seconds 600
      - name: Push api # (callout-5)
        run: |
          chmod +x ../../docker/push_api.sh
          ../../docker/push_api.sh
        shell: bash
      - name: Push web
        run: |
          chmod +x ../../docker/push_web.sh
          ../../docker/push_web.sh
        shell: bash
