name: Build and publish to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo # (callout-1)
        uses: actions/checkout@v2
      - name: Build image api # (callout-2)
        run: |
          export DOCKER_BUILDKIT=1
          docker buildx build --platform linux/amd64 \
               --build-arg API_PORT=3000 \
               --target production \
               -f ./apps/ml-api/Dockerfile \
               -t registry.digitalocean.com/safekids-ai/sq-models-api \
               ..
      - name: Build image web
        run: |
          export DOCKER_BUILDKIT=1
          docker buildx build --platform linux/amd64 \
                 --build-arg API_URL="https://api.snapquiz.ai" \
                 --build-arg WEB_PORT=4200 \
                 --target production \
                 -f "./apps/ml-api-web/Dockerfile" \
                 -t registry.digitalocean.com/safekids-ai/sq-models-web \
                 ..
      - name: Install doctl # (callout-3)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry # (callout-4)
        run: doctl registry login --expiry-seconds 600
      - name: Push api # (callout-5)
        run: |
            export DOCKER_BUILDKIT=1       
            docker buildx build --platform linux/amd64 \
                   --build-arg API_PORT=3000 \
                   --target production \
                   -f ./apps/ml-api/Dockerfile \
                   -t registry.digitalocean.com/safekids-ai/sq-models-api \
                   ..
      - name: Push web
        run: |
            export DOCKER_BUILDKIT=1       
            docker buildx build --platform linux/amd64 \
                   --build-arg API_URL="https://api.snapquiz.ai" \
                   --build-arg WEB_PORT=4200 \
                   --target production \
                   -f "./apps/ml-api-web/Dockerfile" \
                   -t registry.digitalocean.com/safekids-ai/sq-models-web \
                   ..
